// Centralized command list
export const COMMANDS = [
  { cmd: '/toggle', desc: 'Toggle between Interaction and Shell modes' },
  { cmd: '/clear', desc: 'Clear conversation history' },
  { cmd: '/models', desc: 'List available AI models' },
  { cmd: '/switch [key]', desc: 'Switch to a specific model' },
  { cmd: '/help', desc: 'Show help message' },
  { cmd: '/shell [command]', desc: 'Execute a direct shell command securely' },
  { cmd: '/models', desc: 'List all available AI models' },
  { cmd: '/mcp', desc: 'List available MCP tools' },
  { cmd: '/dashboard', desc: 'Show real-time code quality dashboard' },
  { cmd: '/themes', desc: 'Show available visual themes' },
  { cmd: '/add_model', desc: 'Add a custom AI model with API key and endpoint' },
  { cmd: '/mode', desc: 'Alternative command for toggling modes' },
  { cmd: '/keys', desc: 'Show mode switching options' },
  { cmd: '/shortcuts', desc: 'Show mode switching options' },
  { cmd: '/ocr [image_path]', desc: 'Extract text from an image using OCR' },
  { cmd: '/refactor [file_path]', desc: 'Analyze and refactor code in a file' },
  { cmd: '/diff [file1] [file2]', desc: 'Compare two files or directories' },
  { cmd: '/scaffold [name] [template]', desc: 'Generate project scaffolding' },
  { cmd: '/env [action] [variables]', desc: 'Manage environment files' },
  { cmd: '/rename [old] [new] [file]', desc: 'Batch rename variables' },
  { cmd: '/plot [metric]', desc: 'Plot code metrics and data' },
  { cmd: '/update_docs [type] [args]', desc: 'Update documentation files' },
  { cmd: '/snippet [action] [args]', desc: 'Manage code snippets' },
  { cmd: '/scrape [file_or_dir_or_url] [css_selector]', desc: 'Scrape web content' },
  { cmd: '/config [action] [args]', desc: 'Manage configurations' },
  { cmd: '/schedule [task_type] [interval] [target]', desc: 'Schedule tasks to run automatically' },
  { cmd: '/inspect [package]', desc: 'Inspect package information' },
  { cmd: '/context', desc: 'Show current project context information' },
  { cmd: '/set_project [path] [name]', desc: 'Set the current project context' },
  { cmd: '/search [query]', desc: 'Semantic search across the codebase' },
  { cmd: '/find_function [name]', desc: 'Find a function by name' },
  { cmd: '/find_class [name]', desc: 'Find a class by name' },
  { cmd: '/file_context [file_path]', desc: 'Show context for a specific file' },
  { cmd: '/autodetect', desc: 'Auto-detect and set project context' },
  { cmd: '/security_scan', desc: 'Run comprehensive security scan' },
  { cmd: '/secrets_scan', desc: 'Scan for secrets and sensitive information' },
  { cmd: '/vuln_scan', desc: 'Scan for code vulnerabilities' },
  { cmd: '/policy_check', desc: 'Check for policy violations' },
  { cmd: '/security_policy', desc: 'Show current security policy settings' },
  { cmd: '/security_report', desc: 'Generate comprehensive security report' },
  { cmd: '/set_policy [key] [value]', desc: 'Update security policy setting' },
  { cmd: '/plugins', desc: 'List available plugins' },
  { cmd: '/create_plugin [name]', desc: 'Create a new plugin skeleton' },
  { cmd: '/gen_viz', desc: 'Generate all project visualizations' },
  { cmd: '/dep_graph', desc: 'Show dependency graph visualization' },
  { cmd: '/proj_struct', desc: 'Show project structure visualization' },
  { cmd: '/perf_dash', desc: 'Show performance metrics dashboard' },
  { cmd: '/performance', desc: 'Show performance metrics dashboard' },
  { cmd: '/viz_summary', desc: 'Show analysis summary dashboard' },
  { cmd: '/analyze', desc: 'Analyze the current project structure and content' },
  { cmd: '/run_test [file_path]', desc: 'Run a specific test file' },
  { cmd: '/test', desc: 'Run all tests' },
  { cmd: '/exit', desc: 'Exit the application' }
];
